name: Deploy to Droplet

on:
  push:
    branches: [ "main" ]   # change if you deploy from another branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy over SSH (password auth)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ 167.71.215.2 }}
          username: ${{ deploy }}
          password: ${{ Pandamoniom123! }}
          port: 22
          script: |
            /srv/OneTagumVision-DP/deploy.sh
